sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '6'
before_script:
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run cover
  - codecov
  - yarn run build -- -c configurations/example
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
