---
application: CarFreeAtoZ
name: CarFreeAtoZ
domain: carfreeatoz.com

announcements:
  - image: bikeshare-girl.png
    id: 2015-03 Bikeshare Integration
    headline: Now plan your commute with Capital Bikeshare!

organization:
  name: Arlington County Commuter Services
  url: http://carfreeatoz.com

# Support Email Address
email:
  name: CarFreeAtoZ
  address: feedback@carfreeatoz.com

# Survey
survey: https://carfreeatoz.typeform.com/to/gbcagR

# Geocoding
geocode:
  center: -77.105933,38.880148
  zoom: 13
  start_address: 4301 13th St NW Washington, DC 20011
  end_address: 2100 Wilson Blvd, Arlington, VA

# Default application values
api_url: /api
base_url: http://localhost:5000

google_site_verification: d3I8XikSRa0SPOG2b5E62f9c11WPMianJng-PvGkY9E

mapbox_access_token: pk.eyJ1IjoiY29udmV5YWwiLCJhIjoiMDliQURXOCJ9.9JWPsqJY7dGIdX777An7Pw
mapbox_map_id: conveyal.ie3o67m0

otp:
  host: 192.168.59.103
  path: /otp/routers/default
  port: 8080
s3_bucket: ''
segmentio_key: ''
static_url: /assets

# Custom Environments
environments:

  # For running tests
  test:

  # Default & development
  development:
    segmentio_key: egulwcylaa

  # Staging / QA
  staging:
    base_url: http://staging.carfreeatoz.com
    opsworks:
      node_app_id: 1d2d64dd-5ee0-4867-823b-6072e92e297d
      otp_app_id: df14a463-b23b-4121-980d-e625e16af859
      otp_layer_id: 2e98b133-1b0d-4f26-bb5c-5d01649160c3
      stack_id: ea94c5bc-1b73-4e99-a9c4-b5450b40b69a
    otp:
      host: carfreeatoz-otp-staging-245896754.us-east-1.elb.amazonaws.com
      path: /otp/routers/default
      port: 80
    s3_bucket: s3://carfreeatoz-staging/
    segmentio_key: qak98wes8c
    static_url: https://s3.amazonaws.com/carfreeatoz-staging

  # Production envrionment
  production:
    base_url: http://carfreeatoz.com
    opsworks:
      node_app_id: e6d503e7-2ded-49df-a62b-8ac2c000b963
      otp_app_id: dfb0b46d-5b02-4c12-95cc-04a62472cd41
      otp_layer_id: cca53f6a-4048-4655-b9a0-838f568367d5
      stack_id: 3dfd270f-ac17-47ba-b185-f1ed8743590e
    otp:
      host: carfreeatoz-opentripplanner-1020724384.us-east-1.elb.amazonaws.com
      path: /otp/routers/default
      port: 80
    s3_bucket: s3://carfreeatoz/
    segmentio_key: 51cp2qlgkb
    static_url: https://s3.amazonaws.com/carfreeatoz

