application: Modeify
name: Modeify
domain: modeify.co

entries:
  - client/planner-app/index.js:build/planner-app/build.js
  - client/planner-app/style.css:build/planner-app/build.css
  - client/manager-app/index.js:build/manager-app/build.js
  - client/manager-app/style.css:build/manager-app/build.css

announcements:

organization:
  name: Conveyal
  url: http://conveyal.com

# Support Email Address
email:
  name: Trevor Gerhardt
  address: support@conveyal.com

# Geocoding
geocode:
  center: 13.38181499999996,52.516506
  zoom: 13
  start_address: Alexanderplatz, 10178 Berlin
  end_address: Pariser Platz, 10117 Berlin
  boundary_rect:
    min_lat: 13
    min_lon: 52
    max_lat: 14
    max_lon: 53

# Default application values
api_url: /api
base_url: http://localhost:5000

google_site_verification:

mapbox_access_token:
mapbox_base_style:
mapbox_label_style:
mapbox_base_style_manager:

mapzen:
  search:
    api_key:

r5:
  url: http://mock-host.com
s3_bucket: ''
segmentio_key: ''
static_url: /assets

About: >
  ## About

Terms: >
  ## Terms
