application: Modeify
name: Modeify
domain: modeify.co

entries:
  - client/planner-app/index.js:assets/build/planner-app/build.js
  - client/planner-app/style.css:assets/build/planner-app/build.css
  - client/manager-app/index.js:assets/build/manager-app/build.js
  - client/manager-app/style.css:assets/build/manager-app/build.css

announcements:

organization:
  name: Conveyal
  url: http://conveyal.com

# Support Email Address
email:
  name: Trevor Gerhardt
  address: support@conveyal.com

# Geocoding
geocode:
  center: -77.105933,38.880148
  zoom: 13
  start_address: 4301 13th St NW Washington, DC 20011
  end_address: 2100 Wilson Blvd, Arlington, VA
  boundary_rect:
    min_lat: 38.5
    min_lon: -77.5
    max_lat: 39.5
    max_lon: -76.5

# Default application values
api_url: /api
base_url: http://localhost:5000

google_site_verification:

mapbox_access_token:
mapbox_map_id:

mapzen:
  search:
    api_key:

otp:
  host: localhost
  path: /otp/routers/default
  port: 8080
s3_bucket: ''
segmentio_key: ''
static_url: /assets

# Custom Environments
environments:

  # For running tests
  test:

  # Default & development
  development:

  # Staging / QA / Production
  production:
    base_url:
    opsworks:
      otp_app_id:
      otp_layer_id:
      stack_id:
    s3_bucket:
    segmentio_key:
    static_url:
